### PR TITLE
Add urban density dependent speed table based profile

### PR DESCRIPTION
**Pull request by frodrigo**
# Urban Density

## Why
The real speed not only depends of the road type and the maxspeed limit, but also from the context of the road.
A common street limited at 50 Km/h is not the same as a country side road also limited at 50 km/h.
In urban area average speed also depends e.g. on traffic.

The idea is to use multiple speed profiles based of the surounding landuse: country side, urban, industrial area...

## How
Using a databased of land usage, each road segement is splited by the limits of land usage.
A speed profile table is selected for each segement in according to the landuse, then the speed is chooses based on the road type.
Finally, the total duration of the segement is computed and saved in cache to speedup next run of osrm-extract.

### CODE REVIEW

**Comment by daniel-j-h** [comment]
Interesting! What's your experience in using redis and postgres from within the profiles? How fast is it? Did you try larger extracts (e.g. Europe, planet) or are you doing this on a city / region level?


Sidenote: what do you think about creating sub-directories instead of encoding it in the file name?

**Comment by frodrigo** [comment]
It's no so fast. The initial run on Europe take 36h on our setup and with the cache it takes 12h. I will see later if I can make some speed improvement. We have no issues at all with postgres or redis, this part works fine.

**Comment by emiltin** [comment]
we're doing something a little similar for out bike routing service. we first preprocess osm tags during import to a postgis database. in this step we compute 'green scores' for ways and areas based on number of tags (including landuse).

during osrm-extract we query postgis from the profile for each way segment to get surrounding and containing areas/lines of interest and from this compute a green score. 

example fastest vs. greenest route:
http://www.ibikecph.dk/#!/x4ppp.7gfrm/x50h3.7hf00/mode:fast
http://www.ibikecph.dk/#!/x4ppp.7gfrm/x50h3.7hf00/mode:green

code:
https://github.com/ibikecph/osrm-backend/blob/green_v5/profiles/green.lua

**Comment by frodrigo** [comment]
Amend the commit to move all content to a subdirectory.

**Pull request merged**
